version: 2
jobs:
  build:
    working_directory: ~/scanapi
    docker:
      - image: circleci/python:3.7.3
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements-dev.txt
      - run:
          name: Run tests
          command: ./venv/bin/pytest --cov=./ --junit-xml=test-report.xml
      - store_artifacts:
          path: test-report.xml
      - run:
          name: Upload coverage report to codecov.io
          command: ./venv/bin/codecov
