version: 2.1

executors:
  changelog-linter:
    working_directory: /home/circleci/project
    docker:
      - image: rcmachado/changelog:0.6.0

jobs:
  changelog-lint:
    executor: changelog-linter
    steps:
      - checkout
      - run:
          name: Lint changelog
          command: |
            diff CHANGELOG.md <(/changelog fmt CHANGELOG.md) --color -u

workflows:
  version: 2
  master:
    jobs:
      - changelog-lint
