on:
  pull_request:
  push:
    branches:
      - main
name: Lint check
jobs:
  check:
    name: check code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.7.x
      - name: Poetry Setup
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Dependencies
        run: poetry install
      - uses: actions/checkout@v3
      - name: Test Code Lint
        run: |
          make check
