on: pull_request
name: Lint check
jobs:
  black:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Black Code Formatter"
        uses: "./.github/actions/black"
        with:
          args: ". --check"
