on: pull_request
name: Lint check
jobs:
  check:
    name: Lint check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "Black Code Formatter"
        uses: "./.github/actions/black"
        with:
          args: ". --check"
      - name: "Flake8 check"
        uses: TrueBrain/actions-flake8@master
        with:
          ignore: E501,W  # ignore line length check and warnings