name: Publish to Test PyPI
on: pull_request
jobs:
  build-n-publish-test-pypi:
    name: Test PyPI - Build and publish Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Poetry install
        run: |
          pip install -U pip
          pip install poetry
      - name: Run poetry pre-release
        run: |
          make change-version
      - name: Build and publish to test pypi
        uses: JRubics/poetry-publish@v1.2
        with:
          python_version: "3.6"
          poetry_version: ">=0.12"
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"