name: Publish to Test PyPI
on:
  push:
    branches: [master]
jobs:
  build-n-publish-test-pypi:
    name: Test PyPI - Build and publish Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Poetry Setup
        uses: dschep/install-poetry-action@v1.3
        with:
          version: 1.1.1
      - name: Run poetry pre-release
        run: |
          make change-version
      - name: Build and publish to test pypi
        uses: JRubics/poetry-publish@v1.3
        with:
          python_version: "3.6"
          poetry_version: ">=0.12"
          pypi_token: ${{ secrets.TEST_PYPI_TOKEN }}
          repository_name: "testpypi"
          repository_url: "https://test.pypi.org/legacy/"