name: Publish to Test PyPI
on:
  push:
    branches: [main]
jobs:
  build-n-publish-test-pypi:
    name: Test PyPI - Build and publish Python 🐍 distributions 📦
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Poetry Setup
        uses: snok/install-poetry@v1
        with:
          version: 1.3.2
      - name: Run poetry pre-release
        run: |
          make change-version
      - name: Build and publish to test pypi
        run: |
          poetry build
          poetry config pypi-token.testpypi ${{ secrets.TEST_PYPI_TOKEN }}
          poetry config repositories.testpypi "https://test.pypi.org/legacy/"
          poetry publish --repository testpypi
