name: ScanAPI Examples
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  poke-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v3
      - name: Run Examples
        uses: ./.github/actions/run_examples
        with:
          api-name: PokeAPI
          command: "poetry run scanapi run ./examples/pokeapi/scanapi.yaml -c ./examples/pokeapi/scanapi.conf -o pokeapi.html"
          output-path: pokeapi.html

  httpbin-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v3
      - name: Run Examples
        uses: ./.github/actions/run_examples
        with:
          api-name: httpbin.org
          command: "poetry run scanapi run ./examples/httpbin-api/httpbin.yaml -c ./examples/httpbin-api/scanapi.conf -o httpbin.html"
          output-path: httpbin.html

  demo-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ScanAPI repository
        uses: actions/checkout@v3
      - name: Run Examples
        env:
          BASE_URL: "https://demo-api.fly.dev/api/v1/"
          USER: "scanapi-workflow"
          PASSWORD: ${{ secrets.DEMO_API_USER_PASSWORD }}
        uses: ./.github/actions/run_examples
        with:
          api-name: Demo API
          command: "poetry run scanapi run ./examples/demo-api/scanapi.yaml -c ./examples/demo-api/scanapi.conf -o demo-api.html"
          output-path: demo-api.html
